version: '3.8'

services:
  rv-security:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - NET_BROADCAST
    environment:
      - KASA_HOST=10.0.0.188
      - TZ=America/Los_Angeles
      - PST8PDT=PST8PDT
    volumes:
      - ./server:/app/server
    ports:
      - "3001:3001"
      - "5173:5173"
    restart: unless-stopped
